### PR TITLE
Updates the inclusion of snippets to use the full URL

### PR DESCRIPTION
**Pull request by froschdesign**
This is only a _ugly_ and **temporary** workaround. The correct solution is still in progress: https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/11

### CODE REVIEW

**Comment by froschdesign** [comment]
@gsteel 
Is there a better solution to include a raw file from a GitHub repository?

**Comment by gsteel** [comment]
@froschdesign 
I'm not really familiar with PyMdown and have little experience with it, however, I'm assuming that because the docs are being included from `i18n`, the local snippets don't work because the working directory/context is wrong?

As far as I can see, the alternative is either to copy and paste the snippet contents here, or as you've suggested, use the full url, which is a maintenance nightmare with versioning.

What's the argument against standalone docs for this component? For example, the MVC controller plugins are similarly 'small', opt-in components.

**Comment by froschdesign** [comment]
@gsteel 
> …use the full url, which is a maintenance nightmare with versioning.

Right, so the snippets are just a _ugly_ workaround at the moment.
The correct solution is still in progress: https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/11

> What's the argument against standalone docs for this component? For example, the MVC controller plugins are similarly 'small', opt-in components.

The goal is still to keep information together for the reader. At the moment, a lot is fragmented and you have to search too much or coherent explanations are missing.
(Examples: [laminas-paginator and laminas-paginator-adapter-laminasdb](https://docs.laminas.dev/components/#navigation-and-pagination) or [Mezzio and authentication](https://docs.mezzio.dev/#authentication))

This means for the new validators:

- laminas-validator
- laminas-i18n
- laminas-i18n-phone-number

The first two components already create a problem: because a validator is described in laminas-validator, but now laminas-i18n comes up with his own validators. As a new user, you jump between the documentations if you only want to check a value as an integer.
Another separate documentation does not make it any better.

And even if we create separate documentation here, we are only postponing the problem. Because it won't work with laminas-cache and all the adapters.

**Comment by froschdesign** [comment]
By the way, there is a risk that your beautiful new form element will not be found at all. Because it is not listed in the documentation of laminas-form.
And we have to ask ourselves where we look for elements for forms.
You see, we are pushing the information for i18n together, but if that is really the final solution remains questionable.

**Comment by froschdesign** [comment]
I am looking into another workaround which is based on [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin). With this, we would combine everything about telephone numbers in one section of the documentation.

Example:

- Introduction
- Installation
- …
- Phone Numbers:
  - ToE164 Filter
  - ToInternationalPhoneNumber Filter
  - ToNationalPhoneNumber Filter
  - PhoneNumber Form Element
  - PhoneNumber Validator
  - PhoneNumberFormat View Helper

**Comment by froschdesign** [comment]
The related MkDocs plugin has a new version with the required feature: https://github.com/jdoiro3/mkdocs-multirepo-plugin/releases/tag/v0.6.0
I will start with testing.

**Comment by froschdesign** [comment]
@gsteel 
To use the MkDocs plugin "[mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin)" we must add the branch or tag to import the correct content:

> branch={branch}: Tells multirepo what branch (or tag) to use. Defaults to master if not supplied. This is the same argument used in git clone (see [here](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---branchltnamegt)).

https://github.com/jdoiro3/mkdocs-multirepo-plugin#import-statement

Unfortunately, this means that with each release here, changes would also have to be made to the repository of laminas-i18n.
If the plugin supported the default branch, this would not work for us either, because the default branch is always the next feature branch.

Do you have any idea how we can solve this problem?

**Comment by gsteel** [comment]
@froschdesign 

Even if we maintained a dedicated branch and merged into it for every release, it still would not trigger a docs rebuild in `i18n` if I understand correctly.

Could we, instead of triggering a rebuild per repo, per release, generate the docs once per day from a central repo? It might then be feasible to maintain a dedicated branch in repos like this one then?

Sorry I'm not much help here.

**Comment by froschdesign** [comment]
> …it still would not trigger a docs rebuild in `i18n` if I understand correctly.

Correct.

> Could we, instead of triggering a rebuild per repo, per release, generate the docs once per day from a central repo? It might then be feasible to maintain a dedicated branch in repos like this one then?

Generating the documentation per day is a good idea, but then we still have the problem of selecting the right branch. I think we must extend the [update script for the `mkdocs.yml` file](https://github.com/laminas/documentation-theme/blob/48c89f165d6a606557b051566c4c1a599278038b/update_mkdocs_yml.py).

**Comment by froschdesign** [comment]
This will be realised by extending the [update script for the mkdocs.yml file](https://github.com/laminas/documentation-theme/blob/48c89f165d6a606557b051566c4c1a599278038b/update_mkdocs_yml.py).

**Pull request closed without merging**
